name: XCode Tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11.0

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: latest-stable
    - name: Unit Specs
      uses: sersoft-gmbh/xcodebuild-action@v1.3
      with:
        workspace: Example/Legible.xcworkspace
        scheme: Tests
        result-bundle-path: test-results/unit-specs
        build-settings: -test-timeouts-enabled YES
    - name: Save crash reports created since test-results
      if: failure()
      run: find ~/Library/Logs/DiagnosticReports/*.crash -newerBB ./test-results
        -exec cp {} ./test-results \; || true
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2.2.3
      with:
        name: test-results
        path: test-results
