name: XCode Tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Unit Specs
      uses: sersoft-gmbh/xcodebuild-action@v1.3
      with:
        workspace: Example/Legible.xcworkspace
        scheme: Tests
        result-bundle-path: test-results/unit-specs
        build-settings: -test-timeouts-enabled YES
    - name: Save latest crash report
      if: failure()
      run: |
        report=$(ls -tr ~/Library/Logs/DiagnosticReports/ | tail -1)
        cp ~/Library/Logs/DiagnosticReports/${report} ./test-results || true
    - name: Archive results # due to: https://github.com/actions/upload-artifact/issues/76
      if: always()
      run: zip -FSry results.zip test-results || true
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: results.zip
