name: XCode Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Unit Specs
      uses: sersoft-gmbh/xcodebuild-action@v1.3
      with:
        workspace: Example/Legible.xcworkspace
        scheme: Tests
